name: 2024-mdibl-bulk-rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
platforms:
  - linux-64
  - osx-64
dependencies:
  - wget
  - fastp=0.23.2
  - fastqc=0.11.8
  - multiqc=1.14
  - salmon=1.9.0
  - snakemake=7.30.1
