# Adapted from: https://github.com/AlexsLemonade/OpenScPCA-analysis/blob/0d1fc77576a16953f3f15b0d9fd1194bf85cfe5a/.github/workflows/build-push-docker-module.yml
name: Build Docker Image and Push to Dockerhub

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      push-ecr:
        required: true
        type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # set up Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/jaclyn-taroni/2024-mdibl
          tags: type=raw,value=${{ inputs.platform }}

      # Build Docker image and push
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: ${{ inputs.push-ecr }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/${{ inputs.platform }}"
          cache-from: type=gha
